# This file is part of PeachPy package and is licensed under the Simplified BSD license.
#    See license.rst for the full text of the license.

import nervapy
import nervapy.arm.abi
import nervapy.arm.isa
from nervapy.arm.formats import AssemblyFormat, HighRegisterStrategy
from nervapy.arm.function import Function
from nervapy.arm.generic import (ADC, ADCCC, ADCCS, ADCEQ, ADCGE, ADCGT, ADCHI,
                                 ADCHS, ADCLE, ADCLO, ADCLS, ADCLT, ADCMI,
                                 ADCNE, ADCPL, ADCS, ADCSCC, ADCSCS, ADCSEQ,
                                 ADCSGE, ADCSGT, ADCSHI, ADCSHS, ADCSLE,
                                 ADCSLO, ADCSLS, ADCSLT, ADCSMI, ADCSNE,
                                 ADCSPL, ADCSVC, ADCSVS, ADCVC, ADCVS, ADD,
                                 ADDCC, ADDCS, ADDEQ, ADDGE, ADDGT, ADDHI,
                                 ADDHS, ADDLE, ADDLO, ADDLS, ADDLT, ADDMI,
                                 ADDNE, ADDPL, ADDS, ADDSCC, ADDSCS, ADDSEQ,
                                 ADDSGE, ADDSGT, ADDSHI, ADDSHS, ADDSLE,
                                 ADDSLO, ADDSLS, ADDSLT, ADDSMI, ADDSNE,
                                 ADDSPL, ADDSVC, ADDSVS, ADDVC, ADDVS, AND,
                                 ANDCC, ANDCS, ANDEQ, ANDGE, ANDGT, ANDHI,
                                 ANDHS, ANDLE, ANDLO, ANDLS, ANDLT, ANDMI,
                                 ANDNE, ANDPL, ANDS, ANDSCC, ANDSCS, ANDSEQ,
                                 ANDSGE, ANDSGT, ANDSHI, ANDSHS, ANDSLE,
                                 ANDSLO, ANDSLS, ANDSLT, ANDSMI, ANDSNE,
                                 ANDSPL, ANDSVC, ANDSVS, ANDVC, ANDVS, ASR,
                                 B, BCC, BCS, BEQ, BGE, BGT, BHI, BHS, BIC, BICCC,
                                 BICCS, BICEQ, BICGE, BICGT, BICHI, BICHS,
                                 BICLE, BICLO, BICLS, BICLT, BICMI, BICNE,
                                 BICPL, BICS, BICSCC, BICSCS, BICSEQ, BICSGE,
                                 BICSGT, BICSHI, BICSHS, BICSLE, BICSLO,
                                 BICSLS, BICSLT, BICSMI, BICSNE, BICSPL,
                                 BICSVC, BICSVS, BICVC, BICVS, BKPT, BL, BLE,
                                 BLO, BLS, BLT, BLX, BMI, BNE, BPL, BVC, BVS, BX, CMP,
                                 CMPCC, CMPCS, CMPEQ, CMPGE, CMPGT, CMPHI,
                                 CMPHS, CMPLE, CMPLO, CMPLS, CMPLT, CMPMI,
                                 CMPNE, CMPPL, CMPVC, CMPVS, EOR, EORCC, EORCS,
                                 EOREQ, EORGE, EORGT, EORHI, EORHS, EORLE,
                                 EORLO, EORLS, EORLT, EORMI, EORNE, EORPL,
                                 EORS, EORSCC, EORSCS, EORSEQ, EORSGE, EORSGT,
                                 EORSHI, EORSHS, EORSLE, EORSLO, EORSLS,
                                 EORSLT, EORSMI, EORSNE, EORSPL, EORSVC,
                                 EORSVS, EORVC, EORVS, LDMDB, LDMIA, LDR,
                                 LDR_W, LDRB, LDRB_W, LDRD, LDRH, LDRH_W,
                                 LDRSB, LDRSB_W, LDRSH, LDRSH_W, LSL, LSR, MOV,
                                 MOVCC, MOVCS, MOVEQ, MOVGE, MOVGT, MOVHI,
                                 MOVHS, MOVLE, MOVLO, MOVLS, MOVLT, MOVMI,
                                 MOVNE, MOVPL, MOVS, MOVSCC, MOVSCS, MOVSEQ,
                                 MOVSGE, MOVSGT, MOVSHI, MOVSHS, MOVSLE,
                                 MOVSLO, MOVSLS, MOVSLT, MOVSMI, MOVSNE,
                                 MOVSPL, MOVSVC, MOVSVS, MOVT, MOVVC, MOVVS,
                                 MVN, ORR, ORRCC, ORRCS, ORREQ, ORRGE, ORRGT,
                                 ORRHI, ORRHS, ORRLE, ORRLO, ORRLS, ORRLT,
                                 ORRMI, ORRNE, ORRPL, ORRS, ORRSCC, ORRSCS,
                                 ORRSEQ, ORRSGE, ORRSGT, ORRSHI, ORRSHS,
                                 ORRSLE, ORRSLO, ORRSLS, ORRSLT, ORRSMI,
                                 ORRSNE, ORRSPL, ORRSVC, ORRSVS, ORRVC, ORRVS,
                                 POP, POP_W, PUSH, PUSH_W, RSB, RSBCC, RSBCS,
                                 RSBEQ, RSBGE, RSBGT, RSBHI, RSBHS, RSBLE,
                                 RSBLO, RSBLS, RSBLT, RSBMI, RSBNE, RSBPL,
                                 RSBS, RSBSCC, RSBSCS, RSBSEQ, RSBSGE, RSBSGT,
                                 RSBSHI, RSBSHS, RSBSLE, RSBSLO, RSBSLS,
                                 RSBSLT, RSBSMI, RSBSNE, RSBSPL, RSBSVC,
                                 RSBSVS, RSBVC, RSBVS, RSC, RSCCC, RSCCS,
                                 RSCEQ, RSCGE, RSCGT, RSCHI, RSCHS, RSCLE,
                                 RSCLO, RSCLS, RSCLT, RSCMI, RSCNE, RSCPL,
                                 RSCS, RSCSCC, RSCSCS, RSCSEQ, RSCSGE, RSCSGT,
                                 RSCSHI, RSCSHS, RSCSLE, RSCSLO, RSCSLS,
                                 RSCSLT, RSCSMI, RSCSNE, RSCSPL, RSCSVC,
                                 RSCSVS, RSCVC, RSCVS, SBC, SBCCC, SBCCS,
                                 SBCEQ, SBCGE, SBCGT, SBCHI, SBCHS, SBCLE,
                                 SBCLO, SBCLS, SBCLT, SBCMI, SBCNE, SBCPL,
                                 SBCS, SBCSCC, SBCSCS, SBCSEQ, SBCSGE, SBCSGT,
                                 SBCSHI, SBCSHS, SBCSLE, SBCSLO, SBCSLS,
                                 SBCSLT, SBCSMI, SBCSNE, SBCSPL, SBCSVC,
                                 SBCSVS, SBCVC, SBCVS, STMDB, STMIA, STR,
                                 STR_W, STRB, STRB_W, STRD, STRH, STRH_W, SUB,
                                 SUBCC, SUBCS, SUBEQ, SUBGE, SUBGT, SUBHI,
                                 SUBHS, SUBLE, SUBLO, SUBLS, SUBLT, SUBMI,
                                 SUBNE, SUBPL, SUBS, SUBSCC, SUBSCS, SUBSEQ,
                                 SUBSGE, SUBSGT, SUBSHI, SUBSHS, SUBSLE,
                                 SUBSLO, SUBSLS, SUBSLT, SUBSMI, SUBSNE,
                                 SUBSPL, SUBSVC, SUBSVS, SUBVC, SUBVS, TEQ,
                                 TEQCC, TEQCS, TEQEQ, TEQGE, TEQGT, TEQHI,
                                 TEQHS, TEQLE, TEQLO, TEQLS, TEQLT, TEQMI,
                                 TEQNE, TEQPL, TEQVC, TEQVS, TST, TSTCC, TSTCS,
                                 TSTEQ, TSTGE, TSTGT, TSTHI, TSTHS, TSTLE,
                                 TSTLO, TSTLS, TSTLT, TSTMI, TSTNE, TSTPL,
                                 TSTVC, TSTVS, B)
from nervapy.arm.microarchitecture import Microarchitecture
from nervapy.arm.pseudo import (ALIGN, ASSUME, INIT, LABEL, LOAD, REDUCE,
                                RETURN, STORE, SWAP, Label, Loop)
from nervapy.arm.registers import (DRegister, GeneralPurposeRegister,
                                   QRegister, SRegister, WMMXRegister, d0, d1,
                                   d2, d3, d4, d5, d6, d7, d8, d9, d10, d11,
                                   d12, d13, d14, d15, lr, pc, q0, q1, q2, q3,
                                   q4, q5, q6, q7, r0, r1, r2, r3, r4, r5, r6,
                                   r7, r8, r9, r10, r11, r12, s0, s1, s2, s3,
                                   s4, s5, s6, s7, s8, s9, s10, s11, s12, s13,
                                   s14, s15, s16, s17, s18, s19, s20, s21, s22,
                                   s23, s24, s25, s26, s27, s28, s29, s30, s31,
                                   wr0, wr1, wr2, wr3, wr4, wr5, wr6, wr7, wr8,
                                   wr9, wr10, wr11, wr12, wr13, wr14, wr15)
from nervapy.arm.vfpneon import (VABD, VABS, VACGE, VACGT, VACLE, VACLT, VADD,
                                 VADDL, VAND, VBIC, VDIV, VEOR, VFMA, VFMS,
                                 VFNMA, VFNMS, VHADD, VHSUB, VLD1, VLDM,
                                 VLDMDB, VLDMIA, VLDR, VMAX, VMIN, VMLA, VMLS,
                                 VMOV, VMUL, VMULL, VNEG, VNMLA, VNMLS, VNMUL,
                                 VORN, VORR, VPADD, VPMAX, VPMIN, VQADD, VQSUB,
                                 VRECPS, VRHADD, VRSQRTS, VSQRT, VST1, VSTM,
                                 VSTMDB, VSTMIA, VSTR, VSUB, VSUBL, VTST)

__m64 = nervapy.Type("__m64", size=8, is_vector=True, header="mmintrin.h")
