#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Rust Integration Example

Demonstrates how to generate ARM assembly kernels for use in Rust projects,
targeting Cortex-M33 (ARMv8-M.main).

The method is embedded directly in a .rs file with typed externs (no build.rs needed):

       // kernels.rs  (generated by this script)
       core::arch::global_asm!(r#" ... "#);
       unsafe extern "C" {
           pub fn copy_words(src: *const u32, dst: *mut u32, n: usize);
       }
       core::arch::global_asm!(r#" ... "#);
       unsafe extern "C" {
           pub fn accumulate(data: *const u32, n: usize) -> u32;
       }

       // lib.rs
       mod kernels;
"""

import os

from nervapy import *
from nervapy.arm import *
from nervapy.arm.abi import arm_gnueabihf
from nervapy.arm.microarchitecture import Microarchitecture

TARGET = Microarchitecture.CortexM33

def generate_copy_words():
    """Copy n words from src to dst - equivalent to memcpy for aligned u32 arrays."""
    src_arg = Argument(ptr(const_uint32_t))
    dst_arg = Argument(ptr(uint32_t))
    n_arg = Argument(size_t)

    with Function("copy_words", (src_arg, dst_arg, n_arg),
                  target=TARGET, abi=arm_gnueabihf,
                  report_generation=False) as f:

        (src, dst, n) = LOAD.ARGUMENTS()

        with Loop() as loop:
            word = GeneralPurposeRegister()
            LDR(word, [src], 4)
            STR(word, [dst], 4)
            SUBS(n, n, 1)
            BNE(loop.begin)

        RETURN()

    return f


def generate_accumulate():
    """Sum n u32 words and return the total."""
    data_arg = Argument(ptr(const_uint32_t))
    n_arg = Argument(size_t)

    with Function("accumulate", (data_arg, n_arg), uint32_t,
                  target=TARGET, abi=arm_gnueabihf,
                  report_generation=False) as f:

        (data, n) = LOAD.ARGUMENTS()
        acc = GeneralPurposeRegister()
        MOV(acc, 0)

        with Loop() as loop:
            word = GeneralPurposeRegister()
            LDR(word, [data], 4)
            ADD(acc, acc, word)
            SUBS(n, n, 1)
            BNE(loop.begin)

        # Move result into r0 (return register) then return
        from nervapy.arm.registers import r0
        MOV(r0, acc)
        RETURN()

    return f

def write_global_asm_file(functions, path):
    """Write all functions as a Rust file with global_asm!() and typed externs (Option B)."""
    with open(path, "w") as fp:
        fp.write("// Auto-generated by NervaPy - do not edit manually.\n")
        for f in functions:
            fp.write(f.rust_module)
            fp.write("\n")
    print("Wrote: {}".format(path))


if __name__ == "__main__":
    copy_fn = generate_copy_words()
    accum_fn = generate_accumulate()
    functions = [copy_fn, accum_fn]

    write_global_asm_file(functions, os.path.join(os.path.dirname(__file__), "kernels.rs"))
