// Auto-generated by NervaPy - do not edit manually.
core::arch::global_asm!(r#"
	.syntax unified
	.arch armv8-m.main

	.text

.global copy_words
.type copy_words, %function
copy_words:
Lcopy_words.ENTRY:
Lcopy_words.loop_begin:
	LDR r12, [r0], #4
	STR r12, [r1], #4
	SUBS r2, r2, #1
	BNE Lcopy_words.loop_begin
Lcopy_words.loop_end:
	BX lr

"#);

unsafe extern "C" {
    pub fn copy_words(src: *const u32, dst: *mut u32, n: usize);
}

core::arch::global_asm!(r#"
	.syntax unified
	.arch armv8-m.main

	.text

.global accumulate
.type accumulate, %function
accumulate:
Laccumulate.ENTRY:
	MOV r12, #0
Laccumulate.loop_begin:
	LDR r3, [r0], #4
	ADD r12, r12, r3
	SUBS r1, r1, #1
	BNE Laccumulate.loop_begin
Laccumulate.loop_end:
	MOV r0, r12
	BX lr

"#);

unsafe extern "C" {
    pub fn accumulate(data: *const u32, n: usize) -> u32;
}

